server:
 port: 9090
payment:
   baseurl: http://localhost:8090
   authurl: http://localhost:8080/auth/oauth/token
spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
       enabled: true
logging:
  level:
     org:
       apache:
          http: DEBUG
